# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

exclude: "^.*/_vendor/"
repos:
# ruff with --fix should run before other formatting tools
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.11.8"
  hooks:
    # Run the linter.
    - id: "ruff"
      args:
      - "--fix"
      - "--exit-non-zero-on-fix"
    # Run the formatter.
    - id: ruff-format

- repo: "https://github.com/pre-commit/mirrors-clang-format"
  rev: "v20.1.3"
  hooks:
  - id: "clang-format"
    exclude: "^src/cocotb/share/include/(sv_vpi|vhpi|vpi)_user(_ext)?.h"
    types_or: [c, c++]

- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v5.0.0"
  hooks:
  - id: "trailing-whitespace"
  - id: "mixed-line-ending"
    args:
    - "--fix=lf"
  - id: "end-of-file-fixer"
    exclude: "^docs/source/diagrams/(svg|xml)/"

- repo: https://github.com/henryiii/validate-pyproject-schema-store
  rev: "2025.04.28"
  hooks:
    - id: validate-pyproject

- repo: local
  hooks:
  - id: "git-diff"
    name: git diff
    entry: git diff --exit-code
    language: system
    pass_filenames: false
    always_run: true

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    additional_dependencies:
    - pytest
    - coverage
    - nox
    files: ^(src/cocotb/|src/pygpi/|noxfile.py)

ci:
  autofix_prs: false
