# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

exclude: "^.*/_vendor/"
repos:
- repo: "https://github.com/psf/black"
  rev: "23.3.0"
  hooks:
  - id: "black"

- repo: "https://github.com/pycqa/isort"
  rev: "5.12.0"
  hooks:
  - id: "isort"
    args:
    - "--profile=black"

- repo: "https://github.com/pycqa/flake8"
  rev: "6.0.0"
  hooks:
  - id: "flake8"

- repo: "https://github.com/pre-commit/mirrors-clang-format"
  rev: "v16.0.6"
  hooks:
  - id: "clang-format"
    exclude: "^src/cocotb/share/include/(sv_vpi|vhpi|vpi)_user(_ext)?.h"

- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v4.4.0"
  hooks:
  - id: "trailing-whitespace"
  - id: "mixed-line-ending"
    args:
    - "--fix=lf"
  - id: "end-of-file-fixer"
    exclude: "^docs/source/diagrams/(svg|xml)/"
